---
name: Send Message To Homerun
description: Send Message To Homerun w/ curl
inputs:
  url:
    description: "homerun url"
    required: true
  secretToken:
    description: "homerun token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Curl
      shell: bash
      run: |
        curl -k -X POST "${{ inputs.url }}" \
            -H "Content-Type: application/json" \
            -H "X-Auth-Token: ${{ inputs.secretToken }}" \
            -d '{
                  "title": "Memory System Alert",
                  "message": "Memory usage is high",
                  "severity": "warning",
                  "author": "monitoring-system",
                  "timestamp": "2024-5-01T12:00:00Z",
                  "system": "flux",
                  "tags": "cpu,usage,alert",
                  "assigneeaddress": "admin@example.com",
                  "assigneename": "Admin",
                  "artifacts": "Admin",
                  "url": "Admin"
                }'
