---
name: Send Message To Homerun
description: Send Message To Homerun w/ curl
inputs:
  url:
    description: homerun url
    required: true
  secretToken:
    description: homerun token
    required: true
  title:
    description: homerun token
    required: true
  message:
    description: homerun message (body)
    required: true
  severity:
    description: homerun message severity
    required: false
    default: INFO
  system:
    description: source system
    required: false
    default: github

runs:
  using: "composite"
  steps:
    - name: Run Curl
      shell: bash
      run: |
        DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        URL=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}

        curl -k -X POST "${{ inputs.url }}" \
            -H "Content-Type: application/json" \
            -H "X-Auth-Token: ${{ inputs.secretToken }}" \
            -d '{
                  "title": "${{ inputs.title }}",
                  "message": "${{ inputs.message }}",
                  "severity": "${{ inputs.severity }}",
                  "author": "monitoring-system",
                  "timestamp": "${DATE}",
                  "system": "${{ inputs.system }}",
                  "tags": "cpu,usage,alert",
                  "assigneeaddress": "admin@example.com",
                  "assigneename": "Admin",
                  "artifacts": "Admin",
                  "url": "${URL}"
                }'
