---
name: "Curl in Container Action"
description: "Runs a curl command inside a container"
inputs:
  url:
    description: "The URL to send the curl request to"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Curl
      shell: bash
      run: |
        curl ${{ inputs.url }}
