---
name: Send Message To Homerun
description: Send Message To Homerun w/ curl
inputs:
  url:
    description: homerun url
    required: true
  secretToken:
    description: homerun token
    required: true
  title:
    description: homerun token
    required: true
  message:
    description: homerun message (body)
    required: true
  severity:
    description: homerun message severity
    required: false
    default: INFO
  system:
    description: source system
    required: false
    default: github
  artifacts:
    description: artifacts
    required: false
    default: none
  tags:
    description: tags (comma separated)
    required: false
    default: github,actions
  assigneeName:
    description: assignee name
    required: false
    default: ""
  assigneeAddress:
    description: assignee address
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Run Curl
      shell: bash
      run: |
        DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        GH_WF_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

        curl -k -X POST "${{ inputs.url }}" \
            -H "Content-Type: application/json" \
            -H "X-Auth-Token: ${{ inputs.secretToken }}" \
            -d "$(cat <<EOF
        {
          "title": "${{ inputs.title }}",
          "message": "${{ inputs.message }}",
          "severity": "${{ inputs.severity }}",
          "author": "${GITHUB_ACTOR}",
          "timestamp": "${DATE}",
          "system": "${{ inputs.system }}",
          "tags": "${{ inputs.tags }}",
          "assigneeaddress": "${{ inputs.assigneeAddress }}",
          "assigneename": "${{ inputs.assigneeName }}",
          "artifacts": "${{ inputs.artifacts }}",
          "url": "${GH_WF_URL}"
        }
        EOF
        )"
