---
name: Release artifact
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: dagger
      artifact-name:
        required: true
        type: string
      environment-name:
        required: false
        type: string
        default: k8s

jobs:
  release-artifact:
    name: Release artifact on github
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.environment-name }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.artifact-name }}
          path: |-
            /tmp

      - name: Verify artifact
        run: |
          ls -lta /tmp
        shell: bash
