---
name: Run Repository Linting
on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - feature/*
      - fix/*

jobs:
  Lint-Repository:
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-repository-linting.yaml@0d4c5b00e327d24698daf1e696a4f8eab2fc0175 # main
    with:
      runs-on: ubuntu-latest
      environment-name: linting
      app-directory: "./"
      output-file: "/tmp/github-workflow-templates-findings.txt"
      continue-error: "true"
      dagger-version: v0.21.9
      dagger-module-version: v1.17.0
      branch-name: ${{ github.head_ref || github.ref_name }}
    secrets: inherit # pragma: allowlist secret
