---
name: Run Repository Linting
on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - feature/*
      - fix/*

jobs:
  Lint-Repository:
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-repository-linting.yaml@4b2c0fd61777cc4082ce3c33cd47acae23405eb5 # main
    with:
      runs-on: ubuntu-latest
      environment-name: linting
      app-directory: "./"
      output-file: "/tmp/github-workflow-templates-findings.txt"
      continue-error: "true"
      dagger-version: v0.21.10
      # renovate: datasource=github-releases depName=stuttgart-things/blueprints
      dagger-module-version: v3.11.0
      branch-name: ${{ github.head_ref || github.ref_name }}
    secrets: inherit # pragma: allowlist secret
